ConvertFrom-StringData @'
    vaultCredPresent = There is already a value present for {0}, do you wish to update the value?
    codeNone = None (the request passed all filters)
    codeFilteredArtist = Filtered artist
    codeFilteredTrack = Filtered track
    codeTimestampTooFarPast = Timestamp too far in the past
    codeTimestampTooFarFuture = Timestamp too far in the future
    codeScrobblesExceeded = Max daily scrobbles exceeded
    errorFiltered = Request has been filtered because of bad meta data. {0}.
    errorFiltered2 = Request has been filtered because of bad meta data.
    errorCredentials = Could not retrieve credentials for {0}. Run Add-LFMConfiguration with proper keys.
    errorInvalidApiKey = . Run Get-LFMConfiguration if token and session key have already been requested.
    errorInvalidRequest = This is not a valid request.
    errorFunctionImport = Failed to import function {0}
    errorNetworkUnavailable = Last.fm could not be reached. {0}
    errorScrobbleQueueVersion = The scrobble queue at {0} has an unrecognised version ({1}) and cannot be read.
    errorScrobbleQueueNewer = The scrobble queue at {0} was written by version {1} of the queue format and this PowerLFM understands version {2}. Update PowerLFM to read it.
    errorScrobbleQueueNoMigration = The scrobble queue at {0} is at version {1} and there is no migration from version {1} to version {2}, so it cannot be read.
    errorScrobbleQueueMigration = The scrobble queue at {0} could not be migrated from version {1} to version {2}. {3}
    errorScrobbleQueueMigrationEmpty = The migration returned no queue.
    errorScrobbleQueueNoConfiguration = No configuration is loaded, so the scrobble queue cannot record which account a scrobble belongs to. Run Get-LFMConfiguration.
    errorScrobbleQueueResponse = Last.fm returned {1} results for {0} submitted scrobbles.
    errorScrobbleQueueNoChange = A scrobble queue update requires a change to make.
    warningScrobbleQueued = Last.fm could not be reached. {0} - {1} has been added to the scrobble queue.
    warningScrobbleAlreadyQueued = Last.fm could not be reached. {0} - {1} is already in the scrobble queue.
    warningScrobbleQueueLarge = The scrobble queue holds {0} pending scrobbles. Run Send-LFMScrobbleQueue to flush them.
    warningScrobbleQueueLocked = The scrobble queue is in use by another session, so {0} - {1} could not be queued.
    warningScrobbleQueueFailed = The scrobble could not be queued. {0}
    warningScrobbleQueueForeign = {0} pending scrobbles were captured under different credentials and were not flushed. Run Get-LFMScrobbleQueue to inspect them.
    warningScrobbleQueueDropped = Last.fm did not record {0} - {1} at {2} and it has been dropped from the scrobble queue. {3}
    warningScrobbleQueueNotRecorded = Last.fm did not record {0} - {1} at {2} and it is still in the scrobble queue. {3}
    scrobbleQueueTarget = {0} pending scrobbles played between {1} and {2}
    scrobbleQueueEmpty = The scrobble queue is empty.
    scrobbleQueueFlushed = {0} pending scrobbles were recorded by Last.fm.
    scrobbleQueueFlushSkipped = The scrobble queue is in use by another session and was not flushed.
    scrobbleQueueFlushFailed = The scrobble queue could not be flushed. {0}
    scrobbleQueueCleared = The scrobble queue has been cleared.
    scrobbleQueueClearSkipped = The scrobble queue is in use by another session and was not cleared.
    tagAdded = Tag: {0} has been added
    tagRemoved = Tag: {0} has been removed
    trackLoved = Track: {0} has been loved
    trackUnloved = Track: {0} has been unloved
    configInSession = LFMConfig is loaded in to the session
    tokenRequest = Requesting token from {0}
    tokenAuthorizing = Authorizing application with requested token on account
'@
