# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
    LFMApiKey:
        secure: 3hqS76v5ydp1RAfqHveKisX1Cs/xFFOISouteoSO69wUuHVrSrqmi3IPpP/NFQmh
    LFMSessionKey:
        secure: gMAfmqAx9wTyeT5qEDB4zW5N6+GexurGriIaWoupOww1aFZGaDJNxUfbznCpA6PD
    LFMSharedSecret:
        secure: LA1YzNyJRI0WpbZ+HAWU9uXyalNMw3y24+9FHoFeFIHWXX8tm52CBfi/nz84wYke
    NuGetApiKey:
        secure: XFJ8cN2cPIpThLPwSbaTdgsKzVoyg9bbJpafpyxvFcoDNTrKHQ4B4MlfILzZC149

# Allow WMF5 (i.e. PowerShellGallery functionality)
image: Visual Studio 2017

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
    message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
build_script:
    - ps: .\build.ps1 -ResolveDependency -NuGetApiKey $env:NuGetApiKey
