# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  LFMApiKey:
    secure: 3hqS76v5ydp1RAfqHveKisX1Cs/xFFOISouteoSO69wUuHVrSrqmi3IPpP/NFQmh
  LFMSessionKey:
    secure: gMAfmqAx9wTyeT5qEDB4zW5N6+GexurGriIaWoupOww1aFZGaDJNxUfbznCpA6PD
  LFMSharedSecret:
    secure: LA1YzNyJRI0WpbZ+HAWU9uXyalNMw3y24+9FHoFeFIHWXX8tm52CBfi/nz84wYke
  NuGetApiKey:
    secure: XFJ8cN2cPIpThLPwSbaTdgsKzVoyg9bbJpafpyxvFcoDNTrKHQ4B4MlfILzZC149
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

# Allow WMF5 (i.e. PowerShellGallery functionality)
image: Visual Studio 2019

branches:
  only:
    - main
    - master

clone_folder: c:\projects\PowerLFM

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

init:
  - ps: Set-TimeZone -Id 'W. Europe Standard Time' -PassThru

install:
  - ps: Install-Module PSDepend
  - ps: Invoke-PSDepend -Path .\PowerLFM.depend.psd1 -Force

build_script:
  - ps: .\build.ps1 -Task Build

test_script:
  - ps: .\build.ps1 -Task Test
